config/routes.rb
Rails.application.routes.draw do
  get 'forgot', to: "forgot#index"
  post 'forgot', to: "forgot#reset"
  resources :abdos
  resources :cardios
  resources :exercises
  get 'entrainement/aujourdhui', as: :entraineajd
  resources :weapons
  resources :cities
  resources :galons
  resources :soldiers
  resources :comments
  get "my-posts/:title", to: "cats#showcat", as: :mycat
  resources :posts
  resources :cats
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  get 'bycar/index'
  get 'boat/page1'
  root 'welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/abdo.rb
class Abdo < ApplicationRecord
  belongs_to :user
  belongs_to :exercise
end

app/models/cardio.rb
class Cardio < ApplicationRecord
    belongs_to :user
      belongs_to :exercise
end

app/models/cat.rb
class Cat < ApplicationRecord
  has_many :posts
  before_validation do
    self.url=self.name.parameterize
  end
end

app/models/city.rb
class City < ApplicationRecord
  has_many :weapons

  def image=(uploaded_io)
              File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
                        file.write(uploaded_io.read)
                            end
                  write_attribute(:image, uploaded_io.original_filename)
  end
  def image
                read_attribute(:image)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  def self.cardio
    where(mytype: "endurer")
  end
  def self.abdo
    where(mytype: "encaisser")
  end
end

app/models/galon.rb
class Galon < ApplicationRecord
  def image=(uploaded_io)
    write_attribute(:image, uploaded_io.original_filename)
  end
  def image
    read_attribute(:image)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :cat
  belongs_to :user
end

app/models/soldier.rb
class Soldier < ApplicationRecord
  belongs_to :user
  belongs_to :galon

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/weapon.rb
class Weapon < ApplicationRecord
    def image=(uploaded_io)
                    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
                                              file.write(uploaded_io.read)
                                                                          end
                                      write_attribute(:image, uploaded_io.original_filename)
                                        end
      def image
                        read_attribute(:image)
                          end
end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
  before_action :set_weapon, only: %i[ show edit update destroy ]

  # GET /weapons or /weapons.json
  def index
    @weapons = Weapon.all
  end

  # GET /weapons/1 or /weapons/1.json
  def show
  end

  # GET /weapons/new
  def new
    @weapon = Weapon.new
  end

  # GET /weapons/1/edit
  def edit
  end

  # POST /weapons or /weapons.json
  def create
    @weapon = Weapon.new(weapon_params)

    respond_to do |format|
      if @weapon.save
        format.html { redirect_to weapon_url(@weapon), notice: "Weapon was successfully created." }
        format.json { render :show, status: :created, location: @weapon }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @weapon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weapons/1 or /weapons/1.json
  def update
    respond_to do |format|
      if @weapon.update(weapon_params)
        format.html { redirect_to weapon_url(@weapon), notice: "Weapon was successfully updated." }
        format.json { render :show, status: :ok, location: @weapon }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @weapon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weapons/1 or /weapons/1.json
  def destroy
    @weapon.destroy

    respond_to do |format|
      format.html { redirect_to weapons_url, notice: "Weapon was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weapon
      @weapon = Weapon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def weapon_params
      params.require(:weapon).permit(:city_id, :weapon, :name, :image)
    end
end

app/helpers/abdos_helper.rb
module AbdosHelper
end

app/helpers/cardios_helper.rb
module CardiosHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/forgot_helper.rb
module ForgotHelper
end

app/helpers/galons_helper.rb
module GalonsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/soldiers_helper.rb
module SoldiersHelper
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/weapons/_form.html.erb
<%= form_with(model: weapon, html: {class:"myweaponcity"}) do |form| %>
  <% if weapon.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(weapon.errors.count, "error") %> prohibited this weapon from being saved:</h2>

      <ul>
        <% weapon.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.hidden_field :city_id %>
  </div>


  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/weapons/_weapon.html.erb
<div id="<%= dom_id weapon %>">
  <p>
    <strong>City:</strong>
    <%= weapon.city_id %>
  </p>


  <p>
    <strong>Name:</strong>
    <%= weapon.name %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= weapon.image %>
  </p>

</div>

app/views/weapons/edit.html.erb
<h1>Editing weapon</h1>

<%= render "form", weapon: @weapon %>

<br>

<div>
  <%= link_to "Show this weapon", @weapon %> |
  <%= link_to "Back to weapons", weapons_path %>
</div>

app/views/weapons/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Weapons</h1>

  <div class="row row-cols-1 row-cols-md-3 g-4">


  <% @weapons.each do |weapon| %>
      <div class="col">
        <%=link_to weapon do%>
            <div class="card">
              <img src="/uploads/<%=weapon.image%>" class="card-img-top" alt="<%=weapon.name%>">
</div>
<%end%>
</div>
  <% end %>
</div>

<%= link_to "New weapon", new_weapon_path %>

app/views/weapons/new.html.erb
<h1>New weapon</h1>

<%= render "form", weapon: @weapon %>

<br>

<div>
  <%= link_to "Back to weapons", weapons_path %>
</div>

app/views/weapons/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @weapon %>

<div>
  <%= link_to "Edit this weapon", edit_weapon_path(@weapon) %> |
  <%= link_to "Back to weapons", weapons_path %>

  <%= button_to "Destroy this weapon", @weapon, method: :delete %>
</div>