config/routes.rb
Rails.application.routes.draw do
  get 'forgot', to: "forgot#index"
  post 'forgot', to: "forgot#reset"
  resources :abdos
  resources :cardios
  resources :exercises
  get 'entrainement/aujourdhui', as: :entraineajd
  resources :weapons
  resources :cities
  resources :galons
  resources :soldiers
  resources :comments
  get "my-posts/:title", to: "cats#showcat", as: :mycat
  resources :posts
  resources :cats
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  get 'bycar/index'
  get 'boat/page1'
  root 'welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/abdo.rb
class Abdo < ApplicationRecord
  belongs_to :user
  belongs_to :exercise
end

app/models/cardio.rb
class Cardio < ApplicationRecord
    belongs_to :user
      belongs_to :exercise
end

app/models/cat.rb
class Cat < ApplicationRecord
  has_many :posts
  before_validation do
    self.url=self.name.parameterize
  end
end

app/models/city.rb
class City < ApplicationRecord
  has_many :weapons

  def image=(uploaded_io)
              File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
                        file.write(uploaded_io.read)
                            end
                  write_attribute(:image, uploaded_io.original_filename)
  end
  def image
                read_attribute(:image)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  def self.cardio
    where(mytype: "endurer")
  end
  def self.abdo
    where(mytype: "encaisser")
  end
end

app/models/galon.rb
class Galon < ApplicationRecord
  def image=(uploaded_io)
    write_attribute(:image, uploaded_io.original_filename)
  end
  def image
    read_attribute(:image)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :cat
  belongs_to :user
end

app/models/soldier.rb
class Soldier < ApplicationRecord
  belongs_to :user
  belongs_to :galon

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/weapon.rb
class Weapon < ApplicationRecord
    def image=(uploaded_io)
                    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
                                              file.write(uploaded_io.read)
                                                                          end
                                      write_attribute(:image, uploaded_io.original_filename)
                                        end
      def image
                        read_attribute(:image)
                          end
end

app/controllers/soldiers_controller.rb
class SoldiersController < ApplicationController
  before_action :set_soldier, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /soldiers or /soldiers.json
  def index
    @soldiers = Soldier.all
  end

  # GET /soldiers/1 or /soldiers/1.json
  def show
  end

  # GET /soldiers/new
  def new
    @soldier = Soldier.new(user_id: current_user.id)
  end

  # GET /soldiers/1/edit
  def edit
  end

  # POST /soldiers or /soldiers.json
  def create
    @soldier = Soldier.new(soldier_params)

    respond_to do |format|
      if @soldier.save
        format.html { redirect_to soldier_url(@soldier), notice: "Soldier was successfully created." }
        format.json { render :show, status: :created, location: @soldier }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @soldier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /soldiers/1 or /soldiers/1.json
  def update
    respond_to do |format|
      if @soldier.update(soldier_params)
        format.html { redirect_to soldier_url(@soldier), notice: "Soldier was successfully updated." }
        format.json { render :show, status: :ok, location: @soldier }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @soldier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /soldiers/1 or /soldiers/1.json
  def destroy
    @soldier.destroy

    respond_to do |format|
      format.html { redirect_to soldiers_url, notice: "Soldier was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_soldier
      @soldier = Soldier.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def soldier_params
      params.require(:soldier).permit(:name, :image, :user_id, :galon_id, :dateofbirth)
    end
end

app/helpers/abdos_helper.rb
module AbdosHelper
end

app/helpers/cardios_helper.rb
module CardiosHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/forgot_helper.rb
module ForgotHelper
end

app/helpers/galons_helper.rb
module GalonsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/soldiers_helper.rb
module SoldiersHelper
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/soldiers/_form.html.erb
<%= form_with(model: soldier) do |form| %>
  <% if soldier.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(soldier.errors.count, "error") %> prohibited this soldier from being saved:</h2>

      <ul>
        <% soldier.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.hidden_field :user_id %>
  </div>

  <div>
    <%= form.label :galon_id, style: "display: block" %>
    <%= form.select :galon_id, options_for_select(Galon.all.collect{|x|[x.name, x.id, :'data-class' => 'avatar', :'data-style' => "background-image: url('/assets/#{x.image}');background-size:100% 100%;"]}), {}, {id: "CarId2"} %>
  </div>

  <div>
    <%= form.label :dateofbirth, style: "display: block" %>
    <%= form.date_field :dateofbirth %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/soldiers/_soldier.html.erb
<div class="mycard" id="<%= dom_id soldier %>">
  <p>
    <%= soldier.name %>
  </p>

  <p>
  <img src="/uploads/<%= soldier.image %>"/>
  </p>

  <p>
    soldat ajouté par <%= soldier.user.username %>
  </p>

  <p>
    <%= soldier.galon.name %>
  </p>

  <p>
    <strong>né-e le:</strong>
    <%= soldier.dateofbirth %>
  </p>

</div>

app/views/soldiers/edit.html.erb
<h1>Editing soldier</h1>

<%= render "form", soldier: @soldier %>

<br>

<div>
  <%= link_to "Show this soldier", @soldier %> |
  <%= link_to "Back to soldiers", soldiers_path %>
</div>

app/views/soldiers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Soldiers</h1>

<div id="soldiers">
  <% @soldiers.each do |soldier| %>
    <div class="chip">
      <img src="/uploads/<%=soldier.image%>" alt="Person" width="96" height="96">
      <%=soldier.name%>
    <p>
      <%= link_to "Show this soldier", soldier %>
    </p>
    </div>

  <% end %>
</div>

<%= link_to "New soldier", new_soldier_path %>

app/views/soldiers/new.html.erb
<h1>New soldier</h1>

<%= render "form", soldier: @soldier %>

<br>

<div>
  <%= link_to "Back to soldiers", soldiers_path %>
</div>

app/views/soldiers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @soldier %>

<div>
  <%= link_to "Edit this soldier", edit_soldier_path(@soldier) %> |
  <%= link_to "Back to soldiers", soldiers_path %>

  <%= button_to "Destroy this soldier", @soldier, method: :delete %>
</div>